In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats
import math
from sklearn.linear_model import LinearRegression

# Creating Pandas Dataframe from Relative error Reading Data

In [4]:
df_05v = pd.read_csv('../docs/0.5v_1000data_250delay.csv')
df_05v = df_05v["voltage"]
df_3v = pd.read_csv('../docs/3v_1000data_250delay.csv')
df_3v = df_3v["voltage"]
df_6v = pd.read_csv('../docs/6v_1000data_250delay.csv')
df_6v = df_6v["voltage"]
df_9v = pd.read_csv('../docs/9v_1000data_250delay.csv')
df_9v = df_9v["voltage"]
df_12v = pd.read_csv('../docs/12v_1000data_250delay.csv')
df_12v = df_12v["voltage"]
df_15v = pd.read_csv('../docs/15v_1000data_250delay.csv')
df_15v = df_15v["voltage"]
df_18v = pd.read_csv('../docs/18v_1000data_250delay.csv')
df_18v = df_18v["voltage"]
df_21v = pd.read_csv('../docs/21v_1000data_250delay.csv')
df_21v = df_21v["voltage"]
df_24_5v = pd.read_csv('../docs/24.5v_1000data_250delay.csv')
df_24_5v = df_24_5v["voltage"]
df = {
    "0.5v" : [],
    "3v" : [],
    "6v" : [],
    "9v" : [],
    "12v" : [],
    "15v" : [],
    "18v" : [],
    "21v" : [],
    "24.5v" : []
}
for i in df_05v:
    df["0.5v"].append(((i-0.5)/0.5) * 100)
for i in df_3v:
    df["3v"].append(((i-3)/3) * 100)
for i in df_6v:
    df["6v"].append(((i-6)/6) * 100)
for i in df_9v:
    df["9v"].append(((i-9)/9) * 100)
for i in df_12v:
    df["12v"].append(((i-12)/12) * 100)
for i in df_15v:
    df["15v"].append(((i-15)/15) * 100)
for i in df_18v:
    df["18v"].append(((i-18)/18) * 100)
for i in df_21v:
    df["21v"].append(((i-21)/21) * 100)
for i in df_24_5v:
    df["24.5v"].append(((i-24.5)/24.5) * 100)

df = pd.DataFrame(df)
df = df.apply(pd.to_numeric)
df = df.apply(lambda x: x.sort_values().values)
df.to_csv('../docs 2nd Approach/all_voltage.csv', index=False)
df

,0.5v,3v,6v,9v,12v,15v,18v,21v,24.5v
0,-46.0,-17.666667,-6.333333,-3.444444,-2.750000,-2.333333,-1.944444,-1.285714,-5.020408
1,-36.0,-13.000000,-5.666667,-3.111111,-2.333333,-2.200000,-1.666667,-1.190476,-3.551020
2,-36.0,-12.000000,-4.833333,-3.111111,-1.500000,-2.000000,-1.555556,-0.714286,-2.857143
3,-26.0,-9.000000,-4.833333,-2.666667,-1.500000,-1.533333,-1.555556,-0.476190,-2.653061
4,-26.0,-8.000000,-3.166667,-2.333333,-1.333333,-1.533333,-1.555556,-0.476190,-2.530612
...,...,...,...,...,...,...,...,...,...
995,32.0,6.666667,3.000000,2.000000,1.500000,1.533333,1.333333,1.619048,1.959184
996,32.0,7.333333,3.333333,2.222222,1.500000,1.533333,1.333333,1.857143,1.959184
997,32.0,7.333333,3.833333,2.222222,1.750000,1.733333,1.722222,1.857143,1.959184
998,36.0,7.333333,3.833333,2.222222,1.916667,2.066667,1.722222,1.857143,1.959184
999,36.0,9.000000,4.166667,2.222222,2.166667,2.200000,2.388889,2.190476,1.959184

# Generated Z Score from each relative error

In [5]:
for i in df.columns:
    df[i] = (df[i] - df[i].mean()) / df[i].std()

df.to_csv('../docs 2nd Approach/z-score_all_voltage.csv', index=False)
df

,0.5v,3v,6v,9v,12v,15v,18v,21v,24.5v
0,-4.110803,-7.647833,-6.004693,-5.044473,-5.737505,-5.476382,-5.889010,-5.636463,-3.562339
1,-3.156843,-5.616112,-5.347562,-4.535170,-4.898566,-5.197877,-5.158817,-5.351397,-2.558903
2,-3.156843,-5.180744,-4.526149,-4.535170,-3.220688,-4.780120,-4.866739,-3.926068,-2.085058
3,-2.202883,-3.874637,-4.526149,-3.856100,-3.220688,-3.805353,-4.866739,-3.213404,-1.945691
4,-2.202883,-3.439268,-2.883324,-3.346797,-2.885112,-3.805353,-4.866739,-3.213404,-1.862072
...,...,...,...,...,...,...,...,...,...
995,3.330082,2.946141,3.195132,3.274137,2.819675,2.600262,2.727273,3.058043,1.203985
996,3.330082,3.236386,3.523697,3.613672,2.819675,2.600262,2.727273,3.770708,1.203985
997,3.330082,3.236386,4.016545,3.613672,3.323038,3.018019,3.749543,3.770708,1.203985
998,3.711666,3.236386,4.016545,3.613672,3.658614,3.714281,3.749543,3.770708,1.203985
999,3.711666,3.962001,4.345110,3.613672,4.161977,3.992786,5.502008,4.768438,1.203985